# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SiriusA's CTF Writeups
repo_url: https://github.com/Sirius-A/ctf-writeups
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - content.action.view
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/file-document-multiple-outline
    view: material/pencil

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - tags
  - social
